# Generated by Django 5.0.4 on 2024-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banerApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
