# Generated by Django 5.0.4 on 2024-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banerApiApp', '0002_banner_text_banner_title_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(default='https://avito.tech/'),
            preserve_default=False,
        ),
    ]
