# Generated by Django 5.0.4 on 2024-04-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banerApiApp', '0003_alter_banner_text_alter_banner_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
